In [1]:
import pandas as pd

df = pd.DataFrame(

    [[1,2,3],[4,5,6],[7,8,9],[10,11,12]],

    columns=['A','B','C']
    
);

In [2]:
df.head()

    A   B   C
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [3]:
df.tail(2)

    A   B   C
2   7   8   9
3  10  11  12

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
dtypes: int64(3)
memory usage: 228.0 bytes

In [5]:
df.describe()

               A          B          C
count   4.000000   4.000000   4.000000
mean    5.500000   6.500000   7.500000
std     3.872983   3.872983   3.872983
min     1.000000   2.000000   3.000000
25%     3.250000   4.250000   5.250000
50%     5.500000   6.500000   7.500000
75%     7.750000   8.750000   9.750000
max    10.000000  11.000000  12.000000

In [6]:
df.nunique()

A    4
B    4
C    4
dtype: int64

In [7]:
df['B'].unique()

array([ 2,  5,  8, 11])

In [8]:
df.index.tolist()

[0, 1, 2, 3]

In [9]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

In [10]:
df.size

12

In [11]:
df.shape

(4, 3)

In [12]:
coffee = pd.read_csv("~/Manoj (1)/complete-pandas-tutorial-master/complete-pandas-tutorial-master/warmup-data/coffee.csv")

In [13]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [14]:
coffee.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     str
 1   Coffee Type  14 non-null     str
 2   Units Sold   14 non-null     int64
dtypes: int64(1), str(2)
memory usage: 468.0 bytes

In [15]:
coffee.isnull().sum()

Day            0
Coffee Type    0
Units Sold     0
dtype: int64

In [16]:
coffee.describe()

       Units Sold
count   14.000000
mean    32.857143
std      9.346798
min     15.000000
25%     26.250000
50%     35.000000
75%     38.750000
max     45.000000

In [17]:
coffee.columns

Index(['Day', 'Coffee Type', 'Units Sold'], dtype='str')

In [18]:
coffee.index.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [19]:
coffee.size

42

In [20]:
coffee.shape

(14, 3)

In [21]:
coffee.nunique()

Day            7
Coffee Type    2
Units Sold     7
dtype: int64

In [22]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [23]:
coffee.loc[1,"Day"]

'Monday'

In [24]:
coffee.loc[0:5,["Day","Coffee Type"]]

         Day Coffee Type
0     Monday    Espresso
1     Monday       Latte
2    Tuesday    Espresso
3    Tuesday       Latte
4  Wednesday    Espresso
5  Wednesday       Latte

In [25]:
coffee.iloc[0:5,[0,1]]

         Day Coffee Type
0     Monday    Espresso
1     Monday       Latte
2    Tuesday    Espresso
3    Tuesday       Latte
4  Wednesday    Espresso

In [26]:
coffee.at[0,"Day"]

'Monday'

In [27]:
coffee.sample(5)

         Day Coffee Type  Units Sold
1     Monday       Latte          15
2    Tuesday    Espresso          30
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
3    Tuesday       Latte          20

In [28]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [29]:
coffee.sort_values("Units Sold",ascending=False)

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
8      Friday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
11   Saturday       Latte          35
13     Sunday       Latte          35
9      Friday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [30]:
bios = pd.read_csv("~/Manoj (1)/complete-pandas-tutorial-master/complete-pandas-tutorial-master/data/bios.csv")

In [31]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [32]:
bios.loc[bios["weight_kg"] > 70]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
16,17,Guy Forget,1965-01-04,Casablanca,Casablanca-Settat,MAR,France,189.0,79.0,NaN
17,18,Jean-Philippe Gatien,1968-10-16,Alès,Gard,FRA,France,178.0,73.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145464,149191,Joonas Nättinen,1991-01-03,Jämsä,Keski-Suomi,FIN,Finland,189.0,90.0,NaN
145465,149192,Stanislav Galiyev,1992-01-17,Moskva (Moscow),Moskva,RUS,ROC,188.0,82.0,NaN
145466,149193,Mikkel Aagaard,1995-10-18,Frederikshavn,Nordjylland,DEN,Denmark,184.0,81.0,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN
145473,149200,Toms Andersons,1993-11-25,Rīga,Rīga,LAT,Latvia,185.0,86.0,NaN

In [39]:
bios.loc[bios["height_cm"] > 215][["name","height_cm"]]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [41]:
bios[(bios["height_cm"] >  215)  & (bios["born_country"] == 'USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [42]:
bios[bios["name"].str.contains("keith",case  = False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

In [45]:
bios[(bios["born_country"].isin(["IND","USA"])) & bios["name"].str.contains("keith|david",case = False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
2230,2240,David McGowan,1838-01-10,Perry County,Pennsylvania,USA,United States,NaN,NaN,1924-09-22
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
8609,8656,David Diaz,1976-06-07,Chicago,Illinois,USA,United States,167.0,63.0,NaN
8706,8753,David Reid,1973-09-17,Philadelphia,Pennsylvania,USA,United States,175.0,71.0,NaN
11030,11088,David Halpern,1955-08-18,Seattle,Washington,USA,United States,178.0,79.0,NaN
...,...,...,...,...,...,...,...,...,...,...
133419,136358,David Plummer,1985-10-09,Norman,Oklahoma,USA,United States,191.0,95.0,NaN
143533,147186,Tierna Davidson,1998-09-19,Menlo Park,California,USA,United States,178.0,NaN,NaN
143725,147380,David Robertson,1985-04-09,Birmingham,Alabama,USA,United States,180.0,NaN,NaN
143849,147505,David Taylor,1990-12-05,Reno,Nevada,USA,United States,183.0,86.0,NaN
145422,149145,David Warsofsky,1990-05-30,Marshfield,Massachusetts,USA,United States,NaN,NaN,NaN

In [44]:
bios[bios["name"].str.contains("Manoj",case = False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3873,3886,Manoj Pingale,1967-10-22,NaN,NaN,NaN,India,165.0,51.0,NaN
54631,55024,Predrag Manojlović,1951-09-20,Split,Splitsko-dalmatinska županija,CRO,Yugoslavia,190.0,105.0,2014-09-14
118974,120753,Manoj Kumar,1986-12-10,NaN,NaN,NaN,India,172.0,64.0,NaN
121433,123420,Nikola Manojlović,1981-12-01,Beograd (Belgrade),Beograd,SRB,Serbia Serbia and Montenegro,195.0,100.0,NaN

In [49]:
bios[bios["name"].str.startswith("Keith")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN

In [50]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [51]:
coffee["price"] = 4.99

In [52]:
import numpy as np

In [53]:
coffee["new_price"] = np.where(coffee["Coffee Type"] == 'Espresso',3.99,4.99)

In [54]:
coffee.head()

         Day Coffee Type  Units Sold  price  new_price
0     Monday    Espresso          25   4.99       3.99
1     Monday       Latte          15   4.99       4.99
2    Tuesday    Espresso          30   4.99       3.99
3    Tuesday       Latte          20   4.99       4.99
4  Wednesday    Espresso          35   4.99       3.99

In [58]:
coffee.drop(columns="price",inplace= True)

In [59]:
coffee.rename(columns={"new_price":"price"},inplace=True)

In [60]:
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   3.99
1     Monday       Latte          15   4.99
2    Tuesday    Espresso          30   3.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   3.99

In [61]:
coffee["revenue"] = coffee["Units Sold"] * coffee["price"]

In [62]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          15   4.99    74.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   4.99    99.80
4  Wednesday    Espresso          35   3.99   139.65

In [63]:
bios["first_name"] = bios["name"].str.split(" ").str[0]

In [64]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert

In [68]:
bios.query('first_name == "Keith"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN,Keith
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31,Keith
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN,Keith
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09,Keith
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22,Keith
...,...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN,Keith
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN,Keith
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15,Keith
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN,Keith
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN,Keith

In [69]:
bios["born_datetime"] = pd.to_datetime(bios["born_date"])

In [70]:
bios["born_year"] = bios["born_datetime"].dt.year

In [71]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0

In [72]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  str
 2   born_date      143693 non-null  str
 3   born_city      110908 non-null  str
 4   born_region    110908 non-null  str
 5   born_country   110908 non-null  str
 6   NOC            145499 non-null  str
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   str
 10  first_name     145500 non-null  object
 11  born_datetime  143693 non-null  datetime64[us]
 12  born_year      143693 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(1), object(1), str(7)
memory usage: 14.4+ MB

In [73]:
bios.drop(columns="born_date")

,athlete_id,name,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year
0,1,Jean-François Blanchy,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0
1,2,Arnaud Boetsch,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0
2,3,Jean Borotra,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0
3,4,Jacques Brugnon,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0
4,5,Albert Canet,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0
...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002-01-30,2002.0
145496,149223,Valeriya Merkusheva,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999-09-20,1999.0
145497,149224,Yuliya Smirnova,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998-05-08,1998.0
145498,149225,André Foussard,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899-05-19,1899.0
145499,149814,Bill Phillips,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913-07-15,1913.0

In [74]:
bios["height_category"] = bios["height_cm"].apply(lambda  x : "short" if x < 175 else ("Average" if x < 185 else "Tall"))

In [75]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,short
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall

In [76]:
bios_new = bios.copy()

In [80]:
nocs = pd.read_csv("~/Manoj (1)/complete-pandas-tutorial-master/complete-pandas-tutorial-master/data/noc_regions.csv")

In [81]:
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [82]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,short
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall

In [83]:
bios_new = pd.merge(bios,nocs,left_on='born_country',right_on="NOC",how = "left")

In [84]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,short,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall,GBR,UK,NaN

In [85]:
usa = bios[bios["born_country"] == "USA"].copy()
gbr = bios[bios["born_country"] == 'GBR'].copy()

In [ ]:
combined_df = pd.concat([usa,gbr])

In [ ]:
combined_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,Monique,1967-07-22,1967.0,Average
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,Xóchitl,1968-09-17,1968.0,short
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN,Angélica,1973-10-03,1973.0,short
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20,Bert,1897-07-01,1897.0,Tall
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN,Laura,1975-01-06,1975.0,short

In [89]:
bios["born_city"].value_counts()

born_city
Budapest            1378
Moskva (Moscow)      883
Oslo                 708
Stockholm            629
Praha (Prague)       600
                    ...
Tsivilsk               1
Roth                   1
Romoos                 1
Dva Polya Artash       1
Dulwich Hill           1
Name: count, Length: 22368, dtype: int64

In [92]:
coffee.groupby('Coffee Type').agg({'Units Sold':'sum'})

             Units Sold
Coffee Type
Espresso            265
Latte               195

In [93]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,short
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall

In [94]:
pivot = coffee.pivot(columns="Coffee Type",index='Day',values='revenue')

In [95]:
pivot.head()

Coffee Type  Espresso   Latte
Day
Friday         179.55  174.65
Monday          99.75   74.85
Saturday       179.55  174.65
Sunday         179.55  174.65
Thursday       159.60  149.70

In [96]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,short,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall,GBR,UK,NaN

In [97]:
bios_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 17 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   athlete_id       145500 non-null  int64
 1   name             145500 non-null  str
 2   born_date        143693 non-null  str
 3   born_city        110908 non-null  str
 4   born_region      110908 non-null  str
 5   born_country     110908 non-null  str
 6   NOC_x            145499 non-null  str
 7   height_cm        106651 non-null  float64
 8   weight_kg        102070 non-null  float64
 9   died_date        33940 non-null   str
 10  first_name       145500 non-null  object
 11  born_datetime    143693 non-null  datetime64[us]
 12  born_year        143693 non-null  float64
 13  height_category  145500 non-null  str
 14  NOC_y            110639 non-null  str
 15  region           110636 non-null  str
 16  notes            257 non-null     str
dtypes: datetime64[us](1), float64(3), int64(1), object(1), str(11)
memory usage: 18.9+ MB

athlete_id              0
name                    0
born_date            1807
born_city           34592
born_region         34592
born_country        34592
NOC                     1
height_cm           38849
weight_kg           43430
died_date          111560
first_name              0
born_datetime        1807
born_year            1807
height_category         0
dtype: int64

In [104]:
bios["height_cm"] = bios["height_cm"].fillna(bios["height_cm"].mean())

In [105]:
bios.isnull().sum()

athlete_id              0
name                    0
born_date            1807
born_city           34592
born_region         34592
born_country        34592
NOC                     1
height_cm               0
weight_kg           43430
died_date          111560
first_name              0
born_datetime        1807
born_year            1807
height_category         0
dtype: int64

In [103]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,short
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall

In [108]:
bios[bios["name"].notna()]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,176.333724,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.000000,76.0,NaN,Arnaud,1969-04-01,1969.0,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.000000,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.000000,64.0,1978-03-20,Jacques,1895-05-11,1895.0,short
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,176.333724,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.000000,61.0,NaN,Polina,2002-01-30,2002.0,short
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.000000,65.0,NaN,Valeriya,1999-09-20,1999.0,short
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.000000,55.0,NaN,Yuliya,1998-05-08,1998.0,short
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.000000,NaN,1986-03-18,André,1899-05-19,1899.0,short
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,176.333724,NaN,2003-10-20,Bill,1913-07-15,1913.0,Tall

In [109]:
bios_new["month_born"] = bios_new["born_datetime"].dt.month

In [110]:
bios_new["year_born"] = bios_new["born_datetime"].dt.year

In [111]:
bios_new.groupby(["month_born","year_born"])["name"].count().reset_index().sort_values('name',ascending=False)

      month_born  year_born  name
124          1.0     1970.0   239
126          1.0     1972.0   229
129          1.0     1975.0   227
140          1.0     1986.0   227
139          1.0     1985.0   225
...          ...        ...   ...
165          2.0     1853.0     1
168          2.0     1859.0     1
172          2.0     1864.0     1
7            1.0     1852.0     1
1884        12.0     2006.0     1

[1885 rows x 3 columns]

In [113]:
bios_new.groupby(["year_born", "month_born"]).size()

year_born  month_born
1828.0     10.0          1
1831.0     2.0           2
1833.0     1.0           1
1836.0     3.0           1
1837.0     12.0          1
                        ..
2007.0     8.0           1
2008.0     1.0           1
           7.0           1
           8.0           1
2009.0     1.0           1
Length: 1885, dtype: int64

In [116]:
bios_new.groupby([bios_new["year_born"], bios_new["month_born"]]).size()

year_born  month_born
1828.0     10.0          1
1831.0     2.0           2
1833.0     1.0           1
1836.0     3.0           1
1837.0     12.0          1
                        ..
2007.0     8.0           1
2008.0     1.0           1
           7.0           1
           8.0           1
2009.0     1.0           1
Length: 1885, dtype: int64

In [117]:
import janitor

In [118]:
coffee = coffee.clean_names()

In [119]:
coffee.head()

         day coffee_type  units_sold  price  revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          15   4.99    74.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   4.99    99.80
4  Wednesday    Espresso          35   3.99   139.65

In [120]:
from skimpy import skim

In [121]:
skim(coffee)

/home/manoj/Manoj (1)/pandas_practice/.venv/lib/python3.12/site-packages/skimpy/__init__.py:160: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  list(df.select_dtypes(entry).columns)
/home/manoj/Manoj (1)/pandas_practice/.venv/lib/python3.12/site-packages/skimpy/__init__.py:160: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  list(df.select_dtypes(entry).columns)
/home/manoj/Manoj (1)/pandas_practice/.venv/lib/python3.12/site-packages/skimpy/__init__.py:160: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  list(df.select_dtypes(entry).columns)
/home/manoj/Manoj (1)/pandas_practice/.venv/lib/python3.12/site-packages/skimpy/__init__.py:160: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  list(df.select_dtypes(entry).columns)

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 14     │ │ string      │ 2     │                                                          │
│ │ Number of columns │ 5      │ │ float64     │ 2     │                                                          │
│ └───────────────────┴────────┘ │ int64       │ 1     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━┳━━━━━┳━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━┓  │
│ ┃ column        ┃ NA  ┃ NA %   ┃ mean    ┃ sd       ┃ p0      ┃ p25     ┃ p50    ┃ p75    ┃ p100   ┃ hist    ┃  │
│ ┡━━━━━━━━━━━━━━━╇━━━━━╇━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━┩  │
│ │  units_sold   │   0 │      0 │   32.86 │    9.347 │      15 │   26.25 │     35 │  38.75 │     45 │ ▂▂▄▄██  │  │
│ │     price     │   0 │      0 │    4.49 │   0.5189 │    3.99 │    3.99 │   4.49 │   4.99 │   4.99 │ █    █  │  │
│ │    revenue    │   0 │      0 │     145 │    35.67 │   74.85 │     121 │  154.7 │  174.7 │  179.6 │ ▁▃▃▁▃█  │  │
│ └───────────────┴─────┴────────┴─────────┴──────────┴─────────┴─────────┴────────┴────────┴────────┴─────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━━┳━━━━┳━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━┓  │
│ ┃            ┃    ┃      ┃          ┃           ┃          ┃           ┃ chars per  ┃ words per ┃ total      ┃  │
│ ┃ column     ┃ NA ┃ NA % ┃ shortest ┃ longest   ┃ min      ┃ max       ┃ row        ┃ row       ┃ words      ┃  │
│ ┡━━━━━━━━━━━━╇━━━━╇━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━┩  │
│ │    day     │  0 │    0 │  Monday  │ Wednesday │  Friday  │ Wednesday │       7.14 │         1 │         14 │  │
│ │ coffee_typ │  0 │    0 │  Latte   │ Espresso  │ Espresso │   Latte   │        6.5 │         1 │         14 │  │
│ │     e      │    │      │          │           │          │           │            │           │            │  │
│ └────────────┴────┴──────┴──────────┴───────────┴──────────┴───────────┴────────────┴───────────┴────────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

In [127]:
coffee["3day_revenue"] = coffee["revenue"].rolling(3).sum()

In [128]:
coffee.head()

         day coffee_type  units_sold  price  revenue  3day_revenue
0     Monday    Espresso          25   3.99    99.75           NaN
1     Monday       Latte          15   4.99    74.85           NaN
2    Tuesday    Espresso          30   3.99   119.70        294.30
3    Tuesday       Latte          20   4.99    99.80        294.35
4  Wednesday    Espresso          35   3.99   139.65        359.15